## Tutorial Title

_Handling and analyzing spatial, spatiotemporal and movement data_

## Instructor Details

|             |                                                       |
|-------------|-------------------------------------------------------|
|Name:        | Edzer Pebesma                                         |
|             |                                                       |
|Institution: | Institute for Geoinformatics, University of Muenster  |
|             |                                                       |
|Address:     | Heisenbergerstraße 2, Muenster, Germany              |
|             |                                                       |
|Email:       | edzer.pebesma@uni-muenster.de                         |


## Short Instructor Biography

Edzer Pebesma is professor in geoinformatics since 2007.
He is Co-Editor-in-Chief for the [Journal of Statistical
Software](http://www.jstatsoft.org/) and [Computers &
Geosciences](http://www.journals.elsevier.com/computers-and-geosciences),
and associate editor for [Spatial
Statistics](http://www.journals.elsevier.com/spatial-statistics).
He is developer and maintainer of several popular package
packages for handling and analyzing spatial and spatiotemporal
data ([sp](https://cran.rstudio.com/web/packages/sp/index.html),
[spacetime](https://cran.rstudio.com/web/packages/spacetime/index.html),
[trajectories](https://cran.rstudio.com/web/packages/trajectories/index.html),
[gstat](https://cran.rstudio.com/web/packages/gstat/index.html)),
co-author of the book [Applied Spatial Data Analysis
with R, second edition](http://www.asdar-book.org/), and active member of the
[r-sig-geo](http://markmail.org/search/?q=r-sig-geo) community. He
gives regular tutorials on this topic area, for instance during
the yearly [geostat](http://geostat-course.org/) summer schools.
The tutorial material on analyzing trajectory (movement) data is new.

Edzer's google scholar page is found [here](https://scholar.google.de/citations?user=d6jdqdQAAAAJ&hl=en).

## Brief Description of Tutorial

The tutorial will introduce users to the different types of spatial
data (points, lines, polygons, rasters) and demonstrate how they
are read into R. It will also explain how time series data can
be imported, handled and analyzed in R. Then, it will explain
the different types of spatiotemporal data and trajectory data,
and present ways of importing them and analyzing them.

## Goals

The goals of this tutorial are to make participants familiar with

1. basic R packages for handling spatial data (sp, rgdal, rgeos, raster)
2. basic R packages for time series data analysis (zoo, xts)
3. R packages for spatiotemporal analysis (spacetime, trajectories)
4. spatiotemporal fields (continuously varying phenomena), events, objects, and trajectories, and the meaningfulness of analysis methods on each of these
5. strong referencing in R, and how it allows the integration of different data types

In addition, participants will be pointed to further resources (R
packages, CRAN task views, software papers, scientific literature).

## Detailed Outline

Using a small number of use cases, following this sequence, the tutorial will illustrate how to

1. import spatial, temporal, and spatiotemporal data in R
2. map these data structures to and from matrix and data.frame objects
3. work with points, lines, polygons, and rasters
4. work with time series of each of these
5. work with space-time events, and moving objects
6. intersect various spacetime objects, e.g. for spatial and/or temporal selection or for spatial, temporal or spatiotemporal aggregation
7. represent higher concepts such as fields, objects, events, trajectories, and aggregations into the classes, and how to carry out meaningful analysis of these

and give users the opportunity to experiment with this material.

The tutorial consists of three one-hour blocks, where 45 mins
lecturing/demonstration is followed by 15 mins breaks where
participants can try to replicate the analysis, work on their own
data, or start small-group discussions.

Prospective planning: 
* first hour: spatial and temporal
* second hour: spatiotemporal, intersections, aggregations
* third hour: movement data, meaningfulness, data integration

## Justification

1. In recent years, trajectory data (sequences of space-time fixes
for e.g. persons, cars, or animals) have become abundant, and a
source for research and valorisation. This tutorial discusses inference
opportunities arising in different domains, and demonstrates how such data can
be used in spatial statistical analysis methods, (aggregation,
regression modelling, interpolation, and density estimation).
2. Many R packages do not make explicit whether spatial and/or temporal data
refer to continuously varying phenomena (fields), aggregations, or discrete
objects/events. Case studies that illustrate the difference between these will 
improve the ability of participants to choose appropriate analysis methods.
3. All tutorial material will be published on github, and include
executable R scripts with example data. A comprehensive tutorial
with this scope does currently not exist.

## Background Knowledge

Some prior familiarity with handling spatial and/or temporal data
is of benefit, but not required. Familiarity with R is assumed.

## Expected Number of Attendees

30.
