// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_sf_RCPPEXPORTS_H_GEN_
#define RCPP_sf_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace sf {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("sf", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("sf", "sf_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in sf");
            }
        }
    }

    inline Rcpp::NumericVector add_one(Rcpp::NumericVector in) {
        typedef SEXP(*Ptr_add_one)(SEXP);
        static Ptr_add_one p_add_one = NULL;
        if (p_add_one == NULL) {
            validateSignature("Rcpp::NumericVector(*add_one)(Rcpp::NumericVector)");
            p_add_one = (Ptr_add_one)R_GetCCallable("sf", "sf_add_one");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_add_one(Rcpp::wrap(in));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::NumericVector >(rcpp_result_gen);
    }

}

#endif // RCPP_sf_RCPPEXPORTS_H_GEN_
