// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// HexToRaw
RawVector HexToRaw(CharacterVector cx);
RcppExport SEXP sf_HexToRaw(SEXP cxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type cx(cxSEXP);
    __result = Rcpp::wrap(HexToRaw(cx));
    return __result;
END_RCPP
}
