# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPL_get_bbox <- function(sf, depth = 0L) {
    .Call('sf_CPL_get_bbox', PACKAGE = 'sf', sf, depth)
}

CPL_gdal_init <- function() {
    invisible(.Call('sf_CPL_gdal_init', PACKAGE = 'sf'))
}

CPL_gdal_cleanup_all <- function() {
    invisible(.Call('sf_CPL_gdal_cleanup_all', PACKAGE = 'sf'))
}

CPL_gdal_version <- function(what = "RELEASE_NAME") {
    .Call('sf_CPL_gdal_version', PACKAGE = 'sf', what)
}

CPL_crs_parameters <- function(p4s) {
    .Call('sf_CPL_crs_parameters', PACKAGE = 'sf', p4s)
}

CPL_crs_from_epsg <- function(epsg) {
    .Call('sf_CPL_crs_from_epsg', PACKAGE = 'sf', epsg)
}

CPL_crs_from_wkt <- function(wkt) {
    .Call('sf_CPL_crs_from_wkt', PACKAGE = 'sf', wkt)
}

CPL_roundtrip <- function(sfc) {
    .Call('sf_CPL_roundtrip', PACKAGE = 'sf', sfc)
}

CPL_transform <- function(sfc, proj4, epsg) {
    .Call('sf_CPL_transform', PACKAGE = 'sf', sfc, proj4, epsg)
}

CPL_crs_from_proj4string <- function(p4s) {
    .Call('sf_CPL_crs_from_proj4string', PACKAGE = 'sf', p4s)
}

CPL_get_rgdal_drivers <- function(dummy) {
    .Call('sf_CPL_get_rgdal_drivers', PACKAGE = 'sf', dummy)
}

CPL_sfc_from_wkt <- function(wkt) {
    .Call('sf_CPL_sfc_from_wkt', PACKAGE = 'sf', wkt)
}

CPL_area <- function(sfc) {
    .Call('sf_CPL_area', PACKAGE = 'sf', sfc)
}

CPL_gdal_dimension <- function(sfc, NA_if_empty = TRUE) {
    .Call('sf_CPL_gdal_dimension', PACKAGE = 'sf', sfc, NA_if_empty)
}

CPL_length <- function(sfc) {
    .Call('sf_CPL_length', PACKAGE = 'sf', sfc)
}

CPL_gdal_segmentize <- function(sfc, dfMaxLength = 0.0) {
    .Call('sf_CPL_gdal_segmentize', PACKAGE = 'sf', sfc, dfMaxLength)
}

CPL_gdal_linestring_sample <- function(sfc, distLst) {
    .Call('sf_CPL_gdal_linestring_sample', PACKAGE = 'sf', sfc, distLst)
}

CPL_get_layers <- function(datasource, options, do_count = FALSE) {
    .Call('sf_CPL_get_layers', PACKAGE = 'sf', datasource, options, do_count)
}

CPL_read_ogr <- function(datasource, layer, options, quiet = FALSE, iGeomField = 0L, toTypeUser = 0L, promote_to_multi = TRUE, int64_as_string = FALSE) {
    .Call('sf_CPL_read_ogr', PACKAGE = 'sf', datasource, layer, options, quiet, iGeomField, toTypeUser, promote_to_multi, int64_as_string)
}

CPL_write_ogr <- function(obj, dsn, layer, driver, dco, lco, geom, dim, quiet = FALSE) {
    invisible(.Call('sf_CPL_write_ogr', PACKAGE = 'sf', obj, dsn, layer, driver, dco, lco, geom, dim, quiet))
}

CPL_geos_binop <- function(sfc0, sfc1, op, par = 0.0, sparse = TRUE) {
    .Call('sf_CPL_geos_binop', PACKAGE = 'sf', sfc0, sfc1, op, par, sparse)
}

CPL_geos_is_valid <- function(sfc) {
    .Call('sf_CPL_geos_is_valid', PACKAGE = 'sf', sfc)
}

CPL_geos_is_simple <- function(sfc) {
    .Call('sf_CPL_geos_is_simple', PACKAGE = 'sf', sfc)
}

CPL_geos_union <- function(sfc, by_feature = FALSE) {
    .Call('sf_CPL_geos_union', PACKAGE = 'sf', sfc, by_feature)
}

CPL_geos_op <- function(op, sfc, bufferDist = 0.0, nQuadSegs = 30L, dTolerance = 0.0, preserveTopology = FALSE, bOnlyEdges = 1L, dfMaxLength = 0.0) {
    .Call('sf_CPL_geos_op', PACKAGE = 'sf', op, sfc, bufferDist, nQuadSegs, dTolerance, preserveTopology, bOnlyEdges, dfMaxLength)
}

CPL_geos_op2 <- function(op, sfcx, sfcy) {
    .Call('sf_CPL_geos_op2', PACKAGE = 'sf', op, sfcx, sfcy)
}

CPL_geos_version <- function(b = FALSE) {
    .Call('sf_CPL_geos_version', PACKAGE = 'sf', b)
}

CPL_geos_dist <- function(sfc0, sfc1) {
    .Call('sf_CPL_geos_dist', PACKAGE = 'sf', sfc0, sfc1)
}

CPL_geos_relate <- function(sfc0, sfc1) {
    .Call('sf_CPL_geos_relate', PACKAGE = 'sf', sfc0, sfc1)
}

CPL_proj_version <- function(b = FALSE) {
    .Call('sf_CPL_proj_version', PACKAGE = 'sf', b)
}

CPL_proj_is_valid <- function(proj4string) {
    .Call('sf_CPL_proj_is_valid', PACKAGE = 'sf', proj4string)
}

CPL_hex_to_raw <- function(cx) {
    .Call('sf_CPL_hex_to_raw', PACKAGE = 'sf', cx)
}

CPL_raw_to_hex <- function(raw) {
    .Call('sf_CPL_raw_to_hex', PACKAGE = 'sf', raw)
}

CPL_read_wkb <- function(wkb_list, EWKB = FALSE, endian = 0L) {
    .Call('sf_CPL_read_wkb', PACKAGE = 'sf', wkb_list, EWKB, endian)
}

CPL_write_wkb <- function(sfc, EWKB = FALSE, endian = 0L, dim = "XY", precision = 0.0) {
    .Call('sf_CPL_write_wkb', PACKAGE = 'sf', sfc, EWKB, endian, dim, precision)
}

