#' data.frame listing all the simple feature types
#'
#' data.frame listing all simple feature types
#'
sf.types = structure(list(code = c(0L, 1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 
10L, 11L, 12L, 13L, 14L, 15L, 16L, 17L, 1000L, 1001L, 1002L, 
1003L, 1004L, 1005L, 1006L, 1007L, 1008L, 1009L, 1010L, 1011L, 
1012L, 1013L, 1014L, 1015L, 1016L, 1017L, 2000L, 2001L, 2002L, 
2003L, 2004L, 2005L, 2006L, 2007L, 2008L, 2009L, 2010L, 2011L, 
2012L, 2013L, 2014L, 2015L, 2016L, 2017L, 3000L, 3001L, 3002L, 
3003L, 3004L, 3005L, 3006L, 3007L, 3008L, 3009L, 3010L, 3011L, 
3012L, 3013L, 3014L, 3015L, 3016L, 3017L), dim = structure(c(2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 
4L, 4L, 4L, 4L, 4L, 4L, 4L), .Label = c("M", "X2D", "Z", "ZM"
), class = "factor"), type = structure(1:72, .Label = c("Geometry", 
"Point", "LineString", "Polygon", "MultiPoint", "MultiLineString", 
"MultiPolygon", "GeometryCollection", "CircularString", "CompoundCurve", 
"CurvePolygon", "MultiCurve", "MultiSurface", "Curve", "Surface", 
"PolyhedralSurface", "TIN", "Triangle", "Geometry Z", "Point Z", 
"LineString Z", "Polygon Z", "MultiPoint Z", "MultiLineString Z", 
"MultiPolygon Z", "GeometryCollection Z", "CircularString Z", 
"CompoundCurve Z", "CurvePolygon Z", "MultiCurve Z", "MultiSurface Z", 
"Curve Z", "Surface Z", "PolyhedralSurface Z", "TIN Z", "Triangle Z", 
"Geometry M", "Point M", "LineString M", "Polygon M", "MultiPoint M", 
"MultiLineString M", "MultiPolygon M", "GeometryCollection M", 
"CircularString M", "CompoundCurve M", "CurvePolygon M", "MultiCurve M", 
"MultiSurface M", "Curve M", "Surface M", "PolyhedralSurface M", 
"TIN M", "Triangle M", "Geometry ZM", "Point ZM", "LineString ZM", 
"Polygon ZM", "MultiPoint ZM", "MultiLineString ZM", "MultiPolygon ZM", 
"GeometryCollection ZM", "CircularString ZM", "CompoundCurve ZM", 
"CurvePolygon ZM", "MultiCurve ZM", "MultiSurface ZM", "Curve ZM", 
"Surface ZM", "PolyhedralSurface ZM", "TIN ZM", "Triangle ZM"
), class = "factor"), hasM = c(FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), hasZ = c(FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 
TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, 
TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
TRUE, TRUE)), .Names = c("code", "dim", "type", "hasM", "hasZ"
), row.names = c("Geometry", "Point", "LineString", "Polygon", 
"MultiPoint", "MultiLineString", "MultiPolygon", "GeometryCollection", 
"CircularString", "CompoundCurve", "CurvePolygon", "MultiCurve", 
"MultiSurface", "Curve", "Surface", "PolyhedralSurface", "TIN", 
"Triangle", "Geometry Z", "Point Z", "LineString Z", "Polygon Z", 
"MultiPoint Z", "MultiLineString Z", "MultiPolygon Z", "GeometryCollection Z", 
"CircularString Z", "CompoundCurve Z", "CurvePolygon Z", "MultiCurve Z", 
"MultiSurface Z", "Curve Z", "Surface Z", "PolyhedralSurface Z", 
"TIN Z", "Triangle Z", "Geometry M", "Point M", "LineString M", 
"Polygon M", "MultiPoint M", "MultiLineString M", "MultiPolygon M", 
"GeometryCollection M", "CircularString M", "CompoundCurve M", 
"CurvePolygon M", "MultiCurve M", "MultiSurface M", "Curve M", 
"Surface M", "PolyhedralSurface M", "TIN M", "Triangle M", "Geometry ZM", 
"Point ZM", "LineString ZM", "Polygon ZM", "MultiPoint ZM", "MultiLineString ZM", 
"MultiPolygon ZM", "GeometryCollection ZM", "CircularString ZM", 
"CompoundCurve ZM", "CurvePolygon ZM", "MultiCurve ZM", "MultiSurface ZM", 
"Curve ZM", "Surface ZM", "PolyhedralSurface ZM", "TIN ZM", "Triangle ZM"
), class = "data.frame")
